-- Add migration script here
-- table to store password reset requests for the
-- cases where user forget password
CREATE TYPE NOTIFICATION_STATUS AS ENUM ('CREATED', 'EXPIRED', 'DELETED', 'USED');
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_REQUESTS (
    ID UUID PRIMARY KEY NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRES_AFTER INTEGER NOT NULL DEFAULT 900,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    STATUS NOTIFICATION_STATUS NOT NULL DEFAULT 'CREATED',
    USER_ID UUID NOT NULL,
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
