-- Add migration script here
CREATE TABLE IF NOT EXISTS VERIFIED_DOMAINS (
				ID UUID PRIMARY KEY NOT NULL,
				DOMAIN VARCHAR(255) NOT NULL,
				IS_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
				CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
				ADDED_BY UUID NOT NULL,
				CONSTRAINT ADDED_BY_FK FOREIGN KEY (ADDED_BY) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);
