-- Add migration script here

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TYPE IF EXISTS MEMBER_STATUS;
CREATE TYPE MEMBER_STATUS AS ENUM ('VERIFIED', 'SUSPENDED', 'DELETED');

DROP TYPE IF  EXISTS MEMBER_ROLE;
CREATE TYPE MEMBER_ROLE AS ENUM ('ADMIN', 'OWNER', 'MEMBER', 'GUEST');

CREATE TABLE IF NOT EXISTS MEMBERS (
    ID UUID PRIMARY KEY NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    JOINED_AT TIMESTAMP,
    PROFILE_PICTURE VARCHAR(256) NOT NULL DEFAULT '',
    STATUS MEMBER_STATUS NOT NULL DEFAULT 'VERIFIED',
    ROLE MEMBER_ROLE NOT NULL DEFAULT 'MEMBER',
    USER_ID UUID NOT NULL,
    INVITED_BY UUID NOT NULL,
    ROLE_GRANTED_BY UUID,
    WORKSPACE UUID NOT NULL,
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT INVITED_BY_FK FOREIGN KEY (INVITED_BY) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT WORKSPACE_FK FOREIGN KEY (WORKSPACE) REFERENCES WORKSPACES(ID) ON DELETE CASCADE
);
