-- Add migration script here
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TYPE IF EXISTS INVITATION_STATUS;
CREATE TYPE INVITATION_STATUS AS ENUM ('QUEUED', 'INVITED', 'FAILED', 'REJECTED', 'DELETED');

DROP TYPE IF EXISTS TRANSPORT_TYPE;
CREATE TYPE TRANSPORT_TYPE AS ENUM ('EMAIL_CODE', 'PHONE_CODE', 'EMAIL_LINK', 'PHONE_LINK');

DROP TYPE IF EXISTS INVITATION_TYPE;
CREATE TYPE INVITATION_TYPE AS ENUM ('VERIFY_TOKEN', 'MEMBER_INVITATION');

CREATE TABLE IF NOT EXISTS INVITATIONS (
    ID UUID PRIMARY KEY NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL DEFAULT '',
    MSG VARCHAR(1000) NOT NULL DEFAULT '',
    EMAIL VARCHAR(255) NOT NULL DEFAULT '',
    DETAILS VARCHAR(255) NOT NULL DEFAULT '',
    CREATED_BY UUID NOT NULL,
    SENT_TO UUID NOT NULL, 
    WORKSPACE UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    STATUS INVITATION_STATUS NOT NULL DEFAULT 'QUEUED',
    TRANSPORT TRANSPORT_TYPE NOT NULL DEFAULT 'EMAIL_CODE',
    CONSTRAINT CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT SENT_TO_FK FOREIGN KEY (SENT_TO) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT INV_WORKSPACE_FK FOREIGN KEY (WORKSPACE) REFERENCES WORKSPACES(ID) ON DELETE CASCADE
);
