
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TYPE IF EXISTS USER_STATUS;
CREATE TYPE USER_STATUS AS ENUM ('VERIFIED', 'REGISTERED', 'DELETED');

CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL DEFAULT '',
    LAST_NAME VARCHAR(255) NOT NULL DEFAULT '',
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    IP_STR VARCHAR(255) NOT NULL,
    TIMEZONE VARCHAR(65) NOT NULL DEFAULT 'UTC',
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    DELETED BOOL NOT NULL DEFAULT FALSE,
    STATUS USER_STATUS NOT NULL DEFAULT 'REGISTERED'
);
