CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TYPE IF EXISTS WORKSPACE_STATUS;
CREATE TYPE WORKSPACE_STATUS AS ENUM ('VERIFIED', 'UNVERIFIED', 'DISABLED', 'SUSPENDED');

DROP TYPE IF EXISTS WORKSPACE_TYPE;
CREATE TYPE WORKSPACE_TYPE AS ENUM ('B2C_FREE', 'B2B_FREE', 'B2B_PRO', 'B2C_PRO', 'B2B_ENTP');

CREATE TABLE IF NOT EXISTS WORKSPACES (
    ID UUID PRIMARY KEY NOT NULL,
    DISPLAY_PICTURE VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL DEFAULT '',
    DETAILS VARCHAR(255) NOT NULL DEFAULT '',
    COUNTRY_CODE VARCHAR(5),
    COUNTRY VARCHAR(55),
    CREATED_BY UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    DELETED BOOL NOT NULL DEFAULT FALSE,
    STATUS WORKSPACE_STATUS NOT NULL DEFAULT 'UNVERIFIED',
    W_TYPE WORKSPACE_TYPE NOT NULL DEFAULT 'B2C_FREE',
    CONSTRAINT CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
);
