-- Add migration script here

CREATE TABLE IF NOT EXISTS MEMBER_WORKSPACE_DETAILS (
    ID UUID PRIMARY KEY NOT NULL,
    WORKSPACE_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DEFAULT BOOL NOT NULL DEFAULT TRUE,
    IS_FAV BOOL NOT NULL DEFAULT FALSE,
    MEMBER_ID UUID NOT NULL,
    CONSTRAINT MEMBER_ID_FK FOREIGN KEY (MEMBER_ID)  REFERENCES MEMBERS(ID) ON DELETE CASCADE
)