use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct DarkSearchResponse {
    pub number_of_matches_total: u32,
    pub number_of_matches_returned: u32,
    pub documents: Vec<DarkSearchResultItem>,
    pub next_cursor: Option<String>,
    pub warnings: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DarkSearchResultItem {
    pub uuid: Option<String>,
    pub url: Option<String>,
    pub title: Option<String>,
    pub text: serde_json::Value,
    pub authors: Vec<String>,
    pub languge: Option<String>,
    pub published_at: Option<String>,
    pub crawled_at: Option<String>,
    pub updated_at: Option<String>,
    // pub rating: Option<String>,
    pub parent_uuid: Option<String>,
    pub referring_url: Option<String>,
    pub referring_file_type: Option<String>,
    pub site_name: Option<String>,
    pub site_is_live: Option<bool>,
    pub site_domain: Option<String>,
    pub site_type: Option<String>,
    pub site_country: Option<String>,
    pub site_categories: Vec<String>,
    pub thread_url: Option<String>,
    pub thread_uuid: Option<String>,
    pub thread_title: Option<String>,
    pub thread_full_title: Option<String>,
    pub thread_published: Option<String>,
    pub thread_site_section: Option<String>,
    pub thread_section_title: Option<String>,
    pub thread_replies_count: Option<u64>,
    pub thread_participants_count: Option<u64>,
    // pub thread_spam_score: Option<String>,
    pub thread_main_image: Option<String>,
    pub order_in_thread: Option<u64>,
    pub extended_external_links: Vec<String>,
    pub extended_external_images: Vec<String>,
    pub extended_external_videos: Vec<String>,
    pub extended_file_links: Vec<String>,
    pub extended_file_type: Option<String>,
    pub extended_network: Option<String>,
    pub extended_required_login: Option<bool>,
    pub enriched_categories: Vec<String>,
    pub enriched_persons_value: Vec<String>,
    pub enriched_organizations_value: Vec<String>,
    pub enriched_locations_value: Vec<String>,
    pub enriched_emails_value: Vec<String>,
    pub enriched_phones_value: Vec<String>,
    pub enriched_credit_cards_value: Vec<String>,
    pub enriched_ssns_value: Vec<String>,
    pub enriched_wallet_ids_value: Vec<String>,
    pub enriched_ips_value: Vec<String>,
    pub enriched_domains_value: Vec<String>,
}

// DOCS

// {
//   "number_of_matches_total": 2503,
//   "number_of_matches_returned": 1,
//   "documents": [
//     {
//       "uuid": "b8cb191989c0fc0993a0d1a9319af612ae7f0dc4",
//       "url": "http://agarthafw2cock27.onion/item/2028552074172379371#365262e0bd1c0f7fc521464d9b5f44cb",
//       "title": "",
//       "text": "Your my favorite vendor,You have never disappointed me for once.the purity of your Colombian Cocaine powder is unbeatable BEST QUALITY",
//       "authors": ["P****r"],
//       "language": "english",
//       "published_at": "2020-02-02T00:00:00Z",
//       "crawled_at": "2020-06-02T10:51:02Z",
//       "updated_at": "2020-06-02T10:51:02Z",
//       "rating": 5.0,
//       "parent_uuid": "004d39dd1fbfb4ed985f8f56e2d1abe16c51b2ff",
//       "referring_url": "",
//       "referring_file_type": "",
//       "site_name": "Agartha : Underground Anonymous Darknet Marketplace",
//       "site_is_live": true,
//       "site_domain": "agarthafw2cock27.onion",
//       "site_type": "market",
//       "site_country": "",
//       "site_categories": [],
//       "thread_url": "http://agarthafw2cock27.onion/item/2028552074172379371",
//       "thread_uuid": "004d39dd1fbfb4ed985f8f56e2d1abe16c51b2ff",
//       "thread_title": "Stimulants Cocaine 1G A+++ Quality COCAIN",
//       "thread_full_title": "94517.39 DASH: 123.94 HKD: 78431.67 EUR: 9050.57 Stimulants > Cocaine 1G A+++ Quality COCAIN",
//       "thread_published": "2020-06-02T10:50:00Z",
//       "thread_site_section": "http://agarthafw2cock27.onion/listings?page=2667",
//       "thread_section_title": "Agartha : Listings",
//       "thread_replies_count": 24,
//       "thread_participants_count": 3,
//       "thread_spam_score": 0.0,
//       "thread_main_image": "",
//       "order_in_thread": 13,
//       "extended_external_links": [],
//       "extended_external_images": [],
//       "extended_external_videos": [],
//       "extended_file_links": [],
//       "extended_file_type": "html",
//       "extended_network": "tor",
//       "extended_required_login": true,
//       "enriched_categories": ["drugs"],
//       "enriched_persons_value": [],
//       "enriched_organizations_value": [],
//       "enriched_locations_value": [],
//       "enriched_emails_value": [],
//       "enriched_phones_value": [],
//       "enriched_credit_cards_value": [],
//       "enriched_ssns_value": [],
//       "enriched_wallet_ids_value": [],
//       "enriched_ips_value": [],
//       "enriched_domains_value": []
//     }
//   ]
// }
