pub const COUNTRIES_INFO: [[&str; 3]; 230] = [
    ["000webhost", "United States", "USA"],
    ["123RF", "Malaysia", "MYS"],
    ["126", "China", "CHN"],
    ["17Media", "Taiwan", "TWN"],
    ["17173", "China", "CHN"],
    ["2844Breaches", "United States", "USA"],
    ["2fast4u", "Belgium", "BEL"],
    ["500px", "Canada", "CAN"],
    ["7k7k", "China", "CHN"],
    ["8fit", "United States", "USA"],
    ["8tracks", "United States", "USA"],
    ["Abandonia", "Sweden", "SWE"],
    ["Abandonia2022", "Sweden", "SWE"],
    ["AbuseWithUs", "United States", "USA"],
    ["AcneOrg", "United States", "USA"],
    ["Activision", "United States", "USA"],
    ["ActMobile", "United States", "USA"],
    ["Acuity", "United States", "USA"],
    ["Adapt", "United States", "USA"],
    ["Adecco", "Switzerland", "CHE"],
    ["ABFRL", "India", "IND"],
    ["Adobe", "United States", "USA"],
    ["AdultFriendFinder", "United States", "USA"],
    ["AdultFriendFinder2016", "United States", "USA"],
    ["AdultFanFiction", "United States", "USA"],
    ["AdvanceAutoParts", "United States", "USA"],
    ["AerServ", "United States", "USA"],
    ["AgusiQTorrents", "Poland", "POL"],
    ["AhaShare", "United States", "USA"],
    ["AIType", "United States", "USA"],
    ["Aimware", "United States", "USA"],
    ["Aipai", "China", "CHN"],
    ["Ajarn", "Thailand", "THA"],
    ["AKP", "Turkey", "TUR"],
    ["AmartFurniture", "Australia", "AUS"],
    ["Ancestry", "United States", "USA"],
    ["AndroidForums", "United States", "USA"],
    ["AndroidLista", "Spain", "ESP"],
    ["AnimalJam", "United States", "USA"],
    ["AnimeGame", "United States", "USA"],
    ["AnimePlanet", "United States", "USA"],
    ["Animoto", "United States", "USA"],
    ["AntiPublic", "United States", "USA"],
    ["ApexSMS", "United States", "USA"],
    ["APKTW", "Taiwan", "TWN"],
    ["Apollo", "United States", "USA"],
    ["Appartoo", "France", "FRA"],
    ["Appen", "Australia", "AUS"],
    ["Aptoide", "Portugal", "PRT"],
    ["ArmorGames", "United States", "USA"],
    ["ArmyForceOnline", "United States", "USA"],
    ["Artsy", "United States", "USA"],
    ["Artvalue", "France", "FRA"],
    ["AshleyMadison", "Canada", "CAN"],
    ["AstroPID", "United States", "USA"],
    ["AllegedATT", "United States", "USA"],
    ["Aternos", "Germany", "DEU"],
    ["AtlasQuantum", "Brazil", "BRA"],
    ["Atmeltomo", "United States", "USA"],
    ["Audi", "Germany", "DEU"],
    ["Autocentrum", "Poland", "POL"],
    ["Autotrader", "United Kingdom", "GBR"],
    ["Avast", "Czech Republic", "CZE"],
    ["Avito", "Morocco", "MAR"],
    ["Avvo", "United States", "USA"],
    ["B2BUSABusinesses", "United States", "USA"],
    ["BabyNames", "United States", "USA"],
    ["Badoo", "United Kingdom", "GBR"],
    ["BannerBit", "United States", "USA"],
    ["Banorte", "Mexico", "MEX"],
    ["BattlefieldHeroes", "United States", "USA"],
    ["Battlefy", "Canada", "CAN"],
    ["BeautifulPeople", "Denmark", "DNK"],
    ["Bell", "Canada", "CAN"],
    ["Bell2017", "Canada", "CAN"],
    ["Benchmark", "Serbia", "SRB"],
    ["Bestialitysextaboo", "United States", "USA"],
    ["Bhinneka", "Indonesia", "IDN"],
    ["bigbasket", "India", "IND"],
    ["BigMoneyJobs", "United States", "USA"],
    ["BinWeevils", "United Kingdom", "GBR"],
    ["BiohackMe", "United States", "USA"],
    ["BTSec", "China", "CHN"],
    ["BitcoinTalk", "United States", "USA"],
    ["Bitly", "United States", "USA"],
    ["BitTorrent", "United States", "USA"],
    ["BlackHatWorld", "United States", "USA"],
    ["BlackBerryFans", "United States", "USA"],
    ["BlackSpigotMC", "United States", "USA"],
    ["BlankMediaGames", "United States", "USA"],
    ["BleachAnime", "United States", "USA"],
    ["boAt", "India", "IND"],
    ["Bolt", "United States", "USA"],
    ["BombujEu", "United States", "USA"],
    ["Bonobos", "United States", "USA"],
    ["Bookchor", "India", "IND"],
    ["BookCrossing", "United States", "USA"],
    ["Bookmate", "United States", "USA"],
    ["BotOfLegends", "United States", "USA"],
    ["BourseDesVols", "France", "FRA"],
    ["Boxee", "United States", "USA"],
    ["BrandNewTube", "United States", "USA"],
    ["Brazzers", "United States", "USA"],
    ["BreachForums", "United States", "USA"],
    ["BreachForumsClone", "United States", "USA"],
    ["BTCAlpha", "United States", "USA"],
    ["BTCE", "United States", "USA"],
    ["BtoBet", "United States", "USA"],
    ["Bukalapak", "Indonesia", "IDN"],
    ["BulgarianNationalRevenueAgency", "Bulgaria", "BGR"],
    ["BusinessAcumen", "United States", "USA"],
    ["CafeMom", "United States", "USA"],
    ["CafePress", "United States", "USA"],
    ["CannabisForum", "United States", "USA"],
    ["Canva", "Australia", "AUS"],
    ["CapialEconomics", "United States", "USA"],
    ["CardingMafiaDec2021", "United States", "USA"],
    ["CardingMafia", "United States", "USA"],
    ["CashCrate", "United States", "USA"],
    ["Catho", "Brazil", "BRA"],
    ["CDProjektRed", "Poland", "POL"],
    ["CDEK", "Russia", "RUS"],
    ["Chatbooks", "United States", "USA"],
    ["CheapAssGamer", "United States", "USA"],
    ["Chegg", "United States", "USA"],
    ["Chess", "United States", "USA"],
    ["Chowbus", "United States", "USA"],
    ["Cit0day", "United States", "USA"],
    ["CityBee", "Lithuania", "LTU"],
    ["CityJerks", "United States", "USA"],
    ["CivilOnline", "China", "CHN"],
    ["ClashOfKings", "China", "CHN"],
    ["ClearVoiceSurveys", "United States", "USA"],
    ["ClickASnap", "United States", "USA"],
    ["ClixSense", "United States", "USA"],
    ["CloudPets", "United States", "USA"],
    ["ClubPenguinRewritten", "United States", "USA"],
    ["ClubPenguinRewrittenJul2019", "United States", "USA"],
    ["Coachella", "United States", "USA"],
    ["Coinmama", "Israel", "ISR"],
    ["CoinMarketCap", "United States", "USA"],
    ["CoinTracker", "United States", "USA"],
    ["Collection1", "United States", "USA"],
    ["TelegramCombolists", "United States", "USA"],
    ["Comcast", "United States", "USA"],
    ["COMELEC", "Philippines", "PHL"],
    ["CondoCom", "United States", "USA"],
    ["Convex", "Russia", "RUS"],
    ["CouponMomAndArmorGames", "United States", "USA"],
    ["db8151dd", "United States", "USA"],
    ["CrackCommunity", "United States", "USA"],
    ["CrackedTO", "United States", "USA"],
    ["CrackingForum", "United States", "USA"],
    ["CraftRise", "Turkey", "TUR"],
    ["Creative", "United States", "USA"],
    ["CrimeAgencyVBulletin", "United States", "USA"],
    ["CrossFire", "China", "CHN"],
    ["CTARS", "Australia", "AUS"],
    ["CutoutPro", "United States", "USA"],
    ["CyberServe", "Israel", "ISR"],
    ["D3scene", "United States", "USA"],
    ["DaFont", "France", "FRA"],
    ["DailyQuiz", "United States", "USA"],
    ["Dailymotion", "France", "FRA"],
    ["DailyObjects", "United States", "USA"],
    ["Dangdang", "China", "CHN"],
    ["DaniWeb", "United States", "USA"],
    ["DataAndLeads", "United States", "USA"],
    ["PDL", "United States", "USA"],
    ["DataEnrichment", "United States", "USA"],
    ["DataCamp", "United States", "USA"],
    ["DateHotBrunettes", "United States", "USA"],
    ["DatPiff", "United States", "USA"],
    ["Dave", "United States", "USA"],
    ["dBforums", "United States", "USA"],
    ["DCHealth", "United States", "USA"],
    ["Deezer", "France", "FRA"],
    ["DemonForums", "United States", "USA"],
    ["Descomplica", "Brazil", "BRA"],
    ["DevilTorrents", "Poland", "POL"],
    ["devkitPro", "United States", "USA"],
    ["DietCom", "United States", "USA"],
    ["Digimon", "India", "IND"],
    ["Disqus", "United States", "USA"],
    ["DivXSubTitles", "United States", "USA"],
    ["DLH", "Germany", "DEU"],
    ["Dodonew", "China", "CHN"],
    ["Dominos", "Belgium", "BEL"],
    ["DominosIndia", "India", "IND"],
    ["Doomworld", "United States", "USA"],
    ["DoorDash", "United States", "USA"],
    ["Dota2", "United States", "USA"],
    ["Doxbin", "United States", "USA"],
    ["DriveSure", "United States", "USA"],
    ["Drizly", "United States", "USA"],
    ["Dropbox", "United States", "USA"],
    ["Dubsmash", "United States", "USA"],
    ["DucksUnlimited", "United States", "USA"],
    ["DuelingNetwork", "United States", "USA"],
    ["DDO", "United States", "USA"],
    ["Dunzo", "India", "IND"],
    ["Duolingo", "United States", "USA"],
    ["Duowan", "China", "CHN"],
    ["DVDShopCH", "Switzerland", "CHE"],
    ["Dymocks", "Australia", "AUS"],
    ["Eatigo", "Thailand", "THA"],
    ["EatStreet", "United States", "USA"],
    ["ECCIE", "United States", "USA"],
    ["Edmodo", "United States", "USA"],
    ["Elance", "United States", "USA"],
    ["Elanic", "India", "IND"],
    ["ElasticsearchSalesLeads", "United States", "USA"],
    ["Emotet", "United States", "USA"],
    ["Emuparadise", "United States", "USA"],
    ["ECB", "United Kingdom", "GBR"],
    ["EPal", "United States", "USA"],
    ["EpicGames", "United States", "USA"],
    ["EpicBot", "United States", "USA"],
    ["EpicNPC", "United States", "USA"],
    ["Epik", "United States", "USA"],
    ["Eroticy", "United States", "USA"],
    ["Eskimi", "United States", "USA"],
    ["EstanteVirtual", "Brazil", "BRA"],
    ["Estonia", "United States", "USA"],
    ["eThekwiniMunicipality", "South Africa", "ZAF"],
    ["Ethereum", "United States", "USA"],
    ["EuropaJobs", "United States", "USA"],
    ["Evermotion", "United States", "USA"],
    ["EverybodyEdits", "United States", "USA"],
    ["Evite", "United States", "USA"],
];
// pub const COUNTRIES_INFO: [[&str; 3]; 230] = [
//     ["000webhost", "United States", "US"],
//     ["123RF", "Malaysia", "MY"],
//     ["126", "China", "CN"],
//     ["17Media", "Taiwan", "TW"],
//     ["17173", "China", "CN"],
//     ["2844Breaches", "United States", "US"],
//     ["2fast4u", "Belgium", "BE"],
//     ["500px", "Canada", "CA"],
//     ["7k7k", "China", "CN"],
//     ["8fit", "United States", "US"],
//     ["8tracks", "United States", "US"],
//     ["Abandonia", "Sweden", "SE"],
//     ["Abandonia2022", "Sweden", "SE"],
//     ["AbuseWithUs", "United States", "US"],
//     ["AcneOrg", "United States", "US"],
//     ["Activision", "United States", "US"],
//     ["ActMobile", "United States", "US"],
//     ["Acuity", "United States", "US"],
//     ["Adapt", "United States", "US"],
//     ["Adecco", "Switzerland", "CH"],
//     ["ABFRL", "India", "IN"],
//     ["Adobe", "United States", "US"],
//     ["AdultFriendFinder", "United States", "US"],
//     ["AdultFriendFinder2016", "United States", "US"],
//     ["AdultFanFiction", "United States", "US"],
//     ["AdvanceAutoParts", "United States", "US"],
//     ["AerServ", "United States", "US"],
//     ["AgusiQTorrents", "Poland", "PL"],
//     ["AhaShare", "United States", "US"],
//     ["AIType", "United States", "US"],
//     ["Aimware", "United States", "US"],
//     ["Aipai", "China", "CN"],
//     ["Ajarn", "Thailand", "TH"],
//     ["AKP", "Turkey", "TR"],
//     ["AmartFurniture", "Australia", "AU"],
//     ["Ancestry", "United States", "US"],
//     ["AndroidForums", "United States", "US"],
//     ["AndroidLista", "Spain", "ES"],
//     ["AnimalJam", "United States", "US"],
//     ["AnimeGame", "United States", "US"],
//     ["AnimePlanet", "United States", "US"],
//     ["Animoto", "United States", "US"],
//     ["AntiPublic", "United States", "US"],
//     ["ApexSMS", "United States", "US"],
//     ["APKTW", "Taiwan", "TW"],
//     ["Apollo", "United States", "US"],
//     ["Appartoo", "France", "FR"],
//     ["Appen", "Australia", "AU"],
//     ["Aptoide", "Portugal", "PT"],
//     ["ArmorGames", "United States", "US"],
//     ["ArmyForceOnline", "United States", "US"],
//     ["Artsy", "United States", "US"],
//     ["Artvalue", "France", "FR"],
//     ["AshleyMadison", "Canada", "CA"],
//     ["AstroPID", "United States", "US"],
//     ["AllegedATT", "United States", "US"],
//     ["Aternos", "Germany", "DE"],
//     ["AtlasQuantum", "Brazil", "BR"],
//     ["Atmeltomo", "United States", "US"],
//     ["Audi", "Germany", "DE"],
//     ["Autocentrum", "Poland", "PL"],
//     ["Autotrader", "United Kingdom", "GB"],
//     ["Avast", "Czech Republic", "CZ"],
//     ["Avito", "Morocco", "MA"],
//     ["Avvo", "United States", "US"],
//     ["B2BUSABusinesses", "United States", "US"],
//     ["BabyNames", "United States", "US"],
//     ["Badoo", "United Kingdom", "GB"],
//     ["BannerBit", "United States", "US"],
//     ["Banorte", "Mexico", "MX"],
//     ["BattlefieldHeroes", "United States", "US"],
//     ["Battlefy", "Canada", "CA"],
//     ["BeautifulPeople", "Denmark", "DK"],
//     ["Bell", "Canada", "CA"],
//     ["Bell2017", "Canada", "CA"],
//     ["Benchmark", "Serbia", "RS"],
//     ["Bestialitysextaboo", "United States", "US"],
//     ["Bhinneka", "Indonesia", "ID"],
//     ["bigbasket", "India", "IN"],
//     ["BigMoneyJobs", "United States", "US"],
//     ["BinWeevils", "United Kingdom", "GB"],
//     ["BiohackMe", "United States", "US"],
//     ["BTSec", "China", "CN"],
//     ["BitcoinTalk", "United States", "US"],
//     ["Bitly", "United States", "US"],
//     ["BitTorrent", "United States", "US"],
//     ["BlackHatWorld", "United States", "US"],
//     ["BlackBerryFans", "United States", "US"],
//     ["BlackSpigotMC", "United States", "US"],
//     ["BlankMediaGames", "United States", "US"],
//     ["BleachAnime", "United States", "US"],
//     ["boAt", "India", "IN"],
//     ["Bolt", "United States", "US"],
//     ["BombujEu", "United States", "US"],
//     ["Bonobos", "United States", "US"],
//     ["Bookchor", "India", "IN"],
//     ["BookCrossing", "United States", "US"],
//     ["Bookmate", "United States", "US"],
//     ["BotOfLegends", "United States", "US"],
//     ["BourseDesVols", "France", "FR"],
//     ["Boxee", "United States", "US"],
//     ["BrandNewTube", "United States", "US"],
//     ["Brazzers", "United States", "US"],
//     ["BreachForums", "United States", "US"],
//     ["BreachForumsClone", "United States", "US"],
//     ["BTCAlpha", "United States", "US"],
//     ["BTCE", "United States", "US"],
//     ["BtoBet", "United States", "US"],
//     ["Bukalapak", "Indonesia", "ID"],
//     ["BulgarianNationalRevenueAgency", "Bulgaria", "BG"],
//     ["BusinessAcumen", "United States", "US"],
//     ["CafeMom", "United States", "US"],
//     ["CafePress", "United States", "US"],
//     ["CannabisForum", "United States", "US"],
//     ["Canva", "Australia", "AU"],
//     ["CapialEconomics", "United States", "US"],
//     ["CardingMafiaDec2021", "United States", "US"],
//     ["CardingMafia", "United States", "US"],
//     ["CashCrate", "United States", "US"],
//     ["Catho", "Brazil", "BR"],
//     ["CDProjektRed", "Poland", "PL"],
//     ["CDEK", "Russia", "RU"],
//     ["Chatbooks", "United States", "US"],
//     ["CheapAssGamer", "United States", "US"],
//     ["Chegg", "United States", "US"],
//     ["Chess", "United States", "US"],
//     ["Chowbus", "United States", "US"],
//     ["Cit0day", "United States", "US"],
//     ["CityBee", "Lithuania", "LT"],
//     ["CityJerks", "United States", "US"],
//     ["CivilOnline", "China", "CN"],
//     ["ClashOfKings", "China", "CN"],
//     ["ClearVoiceSurveys", "United States", "US"],
//     ["ClickASnap", "United States", "US"],
//     ["ClixSense", "United States", "US"],
//     ["CloudPets", "United States", "US"],
//     ["ClubPenguinRewritten", "United States", "US"],
//     ["ClubPenguinRewrittenJul2019", "United States", "US"],
//     ["Coachella", "United States", "US"],
//     ["Coinmama", "Israel", "IL"],
//     ["CoinMarketCap", "United States", "US"],
//     ["CoinTracker", "United States", "US"],
//     ["Collection1", "United States", "US"],
//     ["TelegramCombolists", "United States", "US"],
//     ["Comcast", "United States", "US"],
//     ["COMELEC", "Philippines", "PH"],
//     ["CondoCom", "United States", "US"],
//     ["Convex", "Russia", "RU"],
//     ["CouponMomAndArmorGames", "United States", "US"],
//     ["db8151dd", "United States", "US"],
//     ["CrackCommunity", "United States", "US"],
//     ["CrackedTO", "United States", "US"],
//     ["CrackingForum", "United States", "US"],
//     ["CraftRise", "Turkey", "TR"],
//     ["Creative", "United States", "US"],
//     ["CrimeAgencyVBulletin", "United States", "US"],
//     ["CrossFire", "China", "CN"],
//     ["CTARS", "Australia", "AU"],
//     ["CutoutPro", "United States", "US"],
//     ["CyberServe", "Israel", "IL"],
//     ["D3scene", "United States", "US"],
//     ["DaFont", "France", "FR"],
//     ["DailyQuiz", "United States", "US"],
//     ["Dailymotion", "France", "FR"],
//     ["DailyObjects", "United States", "US"],
//     ["Dangdang", "China", "CN"],
//     ["DaniWeb", "United States", "US"],
//     ["DataAndLeads", "United States", "US"],
//     ["PDL", "United States", "US"],
//     ["DataEnrichment", "United States", "US"],
//     ["DataCamp", "United States", "US"],
//     ["DateHotBrunettes", "United States", "US"],
//     ["DatPiff", "United States", "US"],
//     ["Dave", "United States", "US"],
//     ["dBforums", "United States", "US"],
//     ["DCHealth", "United States", "US"],
//     ["Deezer", "France", "FR"],
//     ["DemonForums", "United States", "US"],
//     ["Descomplica", "Brazil", "BR"],
//     ["DevilTorrents", "Poland", "PL"],
//     ["devkitPro", "United States", "US"],
//     ["DietCom", "United States", "US"],
//     ["Digimon", "India", "IN"],
//     ["Disqus", "United States", "US"],
//     ["DivXSubTitles", "United States", "US"],
//     ["DLH", "Germany", "DE"],
//     ["Dodonew", "China", "CN"],
//     ["Dominos", "Belgium", "BE"],
//     ["DominosIndia", "India", "IN"],
//     ["Doomworld", "United States", "US"],
//     ["DoorDash", "United States", "US"],
//     ["Dota2", "United States", "US"],
//     ["Doxbin", "United States", "US"],
//     ["DriveSure", "United States", "US"],
//     ["Drizly", "United States", "US"],
//     ["Dropbox", "United States", "US"],
//     ["Dubsmash", "United States", "US"],
//     ["DucksUnlimited", "United States", "US"],
//     ["DuelingNetwork", "United States", "US"],
//     ["DDO", "United States", "US"],
//     ["Dunzo", "India", "IN"],
//     ["Duolingo", "United States", "US"],
//     ["Duowan", "China", "CN"],
//     ["DVDShopCH", "Switzerland", "CH"],
//     ["Dymocks", "Australia", "AU"],
//     ["Eatigo", "Thailand", "TH"],
//     ["EatStreet", "United States", "US"],
//     ["ECCIE", "United States", "US"],
//     ["Edmodo", "United States", "US"],
//     ["Elance", "United States", "US"],
//     ["Elanic", "India", "IN"],
//     ["ElasticsearchSalesLeads", "United States", "US"],
//     ["Emotet", "United States", "US"],
//     ["Emuparadise", "United States", "US"],
//     ["ECB", "United Kingdom", "GB"],
//     ["EPal", "United States", "US"],
//     ["EpicGames", "United States", "US"],
//     ["EpicBot", "United States", "US"],
//     ["EpicNPC", "United States", "US"],
//     ["Epik", "United States", "US"],
//     ["Eroticy", "United States", "US"],
//     ["Eskimi", "United States", "US"],
//     ["EstanteVirtual", "Brazil", "BR"],
//     ["Estonia", "United States", "US"],
//     ["eThekwiniMunicipality", "South Africa", "ZA"],
//     ["Ethereum", "United States", "US"],
//     ["EuropaJobs", "United States", "US"],
//     ["Evermotion", "United States", "US"],
//     ["EverybodyEdits", "United States", "US"],
//     ["Evite", "United States", "US"],
// ];
//
pub fn get_country_code_from_name(name: &str) -> &str {
    for country in COUNTRIES_INFO {
        if country[0] == name {
            return country[2];
        }
    }
    return "USA";
}
